name: Continuous Integration (CI)

on: push


jobs:
  qa:
    name: Quality Assurance with Sonarqube
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:

      - name: Install sonarqube
        run: docker run -d --name sonarqube -p 9000:9000 sonarqube

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Build with Maven skipping tests and with test profile
        run: mvn clean package -DskipTests -Ptest

      - name: Sonarqube scan
        run: |
          mvn sonar:sonar -Dsonar.host.url=http://localhost:9000 -Dsonar.qualitygate.wait=true -Dsonar.login=admin -Dsonar.password=admin


 